require "rubygems"
require "json"
require "rest_client"
require "rhohub/rhohub"
require "rhohub/version"
require "rhohub/base"
require "rhohub/build"
require "rhohub/app"
ENV['rhohub_api_url'] = "http://localhost:3000/api/v1"